common: &common
  type: snowflake
  account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
  password: "{{ env_var('DBT_SNOWFLAKE_PAT') }}"
  user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
  role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
  warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE') }}"
  database: "{{ env_var('DBT_SNOWFLAKE_DATABASE') }}"
  schema: "{{ env_var('DBT_SNOWFLAKE_SCHEMA') }}"
  threads: 4

dbt_data_quality:
  outputs:
    local:
      <<: *common
    prod:
      <<: *common
  target: local


# to run Elementary CLI commands
# for the moment it is configured to run on dev
elementary:
  target: local
  outputs:
    local:
      <<: *common
      schema: elementary
    prod:
      <<: [*common]
      schema: elementary
