[project]
name = "dbt-data-quality"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-snowflake==1.12.0",
]

[project.scripts]
generator_history = "generator.entrypoints.history:main"
generator_new_day = "generator.entrypoints.new_day:main"
generator_status = "generator.entrypoints.status:main"
generator_reset = "generator.entrypoints.reset:main"
generator_create_chaos = "generator.entrypoints.create_chaos:main"
generator_chaos_drop_column = "generator.entrypoints.chaos.drop_column:main"
generator_chaos_duplicate_menu_item = "generator.entrypoints.chaos.duplicate_menu_item:main"
generator_chaos_orphan_menu_item = "generator.entrypoints.chaos.orphan_menu_item:main"
generator_chaos_new_restaurant_volume = "generator.entrypoints.chaos.new_restaurant_volume:main"
generator_chaos_late_restaurant = "generator.entrypoints.chaos.late_restaurant:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = true

[tool.hatch.build.targets.wheel]
packages = ["generator"]

[dependency-groups]
elementary = [
    "elementary-data[databricks]==0.25.1",
]
generator = [
    "faker>=37.0.0",
    "snowflake-connector-python>=3.12.0",
]