name: 'Prepare Environment'
description: 'Prepare the environment (Python & UV) for the workflow'

runs:
  using: "composite"
  steps:
    - name: Cache UV dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          dbt/.venv
          data_generator/.venv
        key: ${{ runner.os }}-uv-${{ hashFiles('dbt/uv.lock', 'dbt/pyproject.toml', 'data_generator/uv.lock', 'data_generator/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv

    - name: Install uv
      uses: ./.github/actions/install-uv

    - name: Install mise
      uses: jdx/mise-action@v2