name: Run dbt & deploy docs

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *' 

permissions:
  contents: write

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare-environment

      - name: Install project dependencies
        run: mise run setup

      - name: Run dbt project
        continue-on-error: true
        env:
          DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
          DBT_SNOWFLAKE_PAT: ${{ secrets.DBT_SNOWFLAKE_PAT }}
          DBT_TARGET: prod
        run: mise run ci:run

      - name: Generate docs
        env:
          DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
          DBT_SNOWFLAKE_PAT: ${{ secrets.DBT_SNOWFLAKE_PAT }}
          DBT_TARGET: prod
        # The Elementary report could fail if we update elementary version and the schema changes
        # So we need to run dbt run --select elementary --target prod (or prod) first
        run: mise run ci:docs

      # Checkout gh-pages and temp subfolder to put the contents we want to keep
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      # Sync dbt and edr docs content only (we want to keep root CNAME/index.html/other static assets)
      # I use a temp dir gh-pages to avoid overwriting directly docs/
      - name: Sync docs
        run: |
          rm -rf gh-pages/docs/dbt_docs gh-pages/docs/elementary_report
          cp -r docs/dbt_docs gh-pages/docs/
          cp -r docs/elementary_report gh-pages/docs/
          cd gh-pages
          git add docs/dbt_docs docs/elementary_report
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update dbt & Elementary docs" || echo "No changes to commit"
          git push origin gh-pages